travis:
  secure:
    BINSTAR_TOKEN: SOnm4BYLxlt3CvY47RXShdQo71/y1L6yFkC3dAoHO7e8RqrUBO722SLCJFukGoD1bp22m7UL8T0PFBQDWvIDPsAsZuX2XBZ9/XvBrR9FCBEmfhp/343IF5U1lRjKlsUGnESuT0Yj87eBNT2nQ72u4LF9coiR6AtjEPdlJlC/ti6c160uUCjJdLM4gwUKfQog2MfI5URhwIK+zK0WXX5eUP/C84ldYGpLUQ9mbAb1Gm3T8a0Fz4bvWmAqUtEOqnuFiXUa8m0aKbVBi5B97nvVnuw9noIB2N+yFdJqOvby0Dm1lpld9phFVYJ9WwSojvKlbbFAhJgGA1X7xD66LQRLVon0N2aEyuiYxut9KBxtDsyszWcWVngvBeIVg3DbFM5bsV7ZQ4b6aNsvmqF12cUwFRSGQUZxDD2SN5G/DhmsVPpUsz34GWI7QHuWAqLt6wWzXDEoeEYrxL5oJw4ursdyhxKo2xO1xMNYQhp32eynYbEmhwXaW9G1bpCMScWAJo5e/hgloVs5swAUkSsP70kc1hTGd3KS0eO6Ty4AZKFdPGgPCDHx2sSiwMcwjj0FdtusGA7CHvdz8QxozqIjUdPWeF+fFRjpvVkln0Gs2fm2pWcDtGd4y03EBgpLi/1q9OxQEj7hoHrSTOdVrLOgqxV9WLUCkknYao0BDbuey005FxU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
